### ISSUE TITLE
Create DORA Dashboard

### ISSUE THREAD

**Issue by yusufscott** [liatrio/o11y-demo#17]
Create a dashboard to display DORA metrics in Grafana
```[tasklist]
### Tasks
- [ ] Create Deployment Frequency table
- [ ] Create Lead Time for Changes table
- [ ] Create Change Failure Rate table
- [ ] Create Time to Restore Service table
```

**Comment by adrielp** [comment]
Closing this out as this work has been done as part of the DORA metrics MVP. Future work will be created as needed.
